# -*- coding: utf-8 -*-
"""ZAHARA NANSAMBA_2022/DSCE/030/SS.ipyn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5u05avQ7--s1v1MFO7M2f0fPb6omPD6

## TEST Preamble:

This test assignment, has two sections *Probability Theory & Linear Algebra*, Probability is the mathematical field that enables us to quantify uncertainty as well as to make predictions despite uncertainty. While *Linear Algebra is basically Matrix and Vector Operations*, that builds on the basics of linear algebra as learned in theory.

## Instructions

* Your are to free to setup your own Jupyter Notebook, and supply all the answers to the questions inthere or work from the one I have provided.
* Attempt all questions in **Section 1** and **At least 4** from **Section 2**, and as many as you can from the last section **optional Section**

## By Assessing the context and questions in this test assignment

Import all the relevant libraries you may need in the course of this assignment
"""

# import all the neccessary libraries needed (Max 2.5 marks allowed)

"""## Section 1: Introduction to Probability

### What Probability Theory Is!

### Here below is a quick review of probability and Combinatorial. Go through carefully and pick a leaf to answer the questions at the end

#### Events and Sample Spaces

Let's assume we have a fair coin, which is equally likely to come up heads (H) or tails (T).

In instances like this, where the two outcomes are equally likely, we can use probability theory to express the likelihood of a particular **event** by comparing it with the **sample space** (the set of all possible outcomes; can be denoted as $\Omega$):

$$ P(\text{event}) = \frac{\text{# of outcomes of event}}{\text{# of outcomes in }\Omega} $$

If we're only flipping the coin once, then there are only two possible outcomes in the sample space $\Omega$: it will either be H or T (using set notation, we could write this as $\Omega$ = {H, T}).

Therefore: $$ P(H) = \frac{1}{2} = 0.5 $$

Equally: $$ P(T) = \frac{1}{2} = 0.5 $$

As a separate example, consider drawing a single card from a standard deck of 52 playing cards. In this case, the number of possible outcomes in the sample space $\Omega$ is 52.

There is only one ace of spades in the deck, so the probability of drawing it is: $$ P(\text{ace of spades}) = \frac{1}{52} \approx 0.019 $$

In contrast there are four aces, so the probability of drawing an ace is: $$ P(\text{ace}) = \frac{4}{52} \approx 0.077 $$

Some additional examples: 
$$ P(\text{spade}) = \frac{13}{52} = 0.25 $$
$$ P(\text{ace OR spade}) = \frac{16}{52} \approx 0.307 $$
$$ P(\text{card}) = \frac{52}{52} = 1 $$
$$ P(\text{turnip}) = \frac{0}{52} = 0 $$

#### Multiple Independent Observations

Let's return to coin flipping to illustrate situations where we have an event consisting of multiple independent observations. For example, the probability of throwing two consecutive heads is: $$ P(\text{HH}) = \frac{1}{4} = 0.25 $$ ...because there is one HH event in the sample set of four possible events ($\Omega$ = {HH, HT, TH, TT}).

Likewise, the probability of throwing *three* consecutive heads is: $$ P(\text{HHH}) = \frac{1}{8} = 0.125 $$ ...because there is one HHH event in the sample set of eight possible events ($\Omega$ = {HHH, HHT, HTH, THH, HTT, THT, TTH, TTT}).

As final examples, the probability of throwing exactly two heads in three tosses is $ P = \frac{3}{8} = 0.375 $ while the probability of throwing at least two heads in three tosses is $ P = \frac{4}{8} = 0.5 $.

#### Combining Probabilities

In order to combine probabilities, we can multiply them. So the probability of throwing five consecutive heads, for example, is the product of probabilities we've already calculated: $$ P(\text{HHHHH}) = P(\text{HH}) \times P(\text{HHH}) = \frac{1}{4} \times \frac{1}{8} = \frac{1}{32} \approx 0.031 $$

#### Combinatorics

*Combinatorics* is a field of mathematics devoted to counting that can be helpful to studying probabilities. We can use **factorials** (e.g., $4! = 4 \times 3 \times 2 \times 1 = 24$), which feature prominently in combinatorics, to calculate probabilities instead of painstakingly determining all of the members of the sample space $\Omega$ and counting subsets within $\Omega$.

More specifically, we can calculate the number of outcomes of an event using the "number of combinations" equation: $$ {n \choose k} = \frac{n!}{k!(n - k)!} $$

The left-hand side of the equation is read "$n$ choose $k$" and is most quickly understood via an example: If we have three coin flips, $n = 3$, and if we're interested in the number of ways to get two head flips (or two tail flips, for that matter), $k = 2$. We would read this as "3 choose 2" and calculate it as:
$$ {n \choose k} = {3 \choose 2} = \frac{3!}{2!(3 - 2)!} = \frac{3!}{(2!)(1!)} = \frac{3 \times 2 \times 1}{(2 \times 1)(1)} = \frac{6}{(2)(1)} = \frac{6}{2} = 3 $$

This provide us with the numerator for event-probability equation from above: $$ P(\text{event}) = \frac{\text{# of outcomes of event}}{\text{# of outcomes in }\Omega} $$

In the case of coin-flipping (or any binary process with equally probable outcomes), the denominator can be calculated with $2^n$ (where $n$ is again the number of coin flips), so: $$ \frac{\text{# of outcomes of event}}{\text{# of outcomes in }\Omega} = \frac{3}{2^n} = \frac{3}{2^3} = \frac{3}{8} = 0.375 $$

## Section 2: Attemppt at least 4 Questions from this section

### Question 2: Moments of Probability : Expected Value

**Exercises**:

1. Assuming heads = 1 and tails = 0, what’s the expected value of the toss of a fair coin? 
2. ...and of two tosses of a fair coin? 
3. You are one of a thousand people to purchase a lottery ticket. The ticket costs \\$10 and pays out \\$5000. What value should you expect from this transaction?

### Question 3: Probability Distributions

### a). Binomial Distribution

All distributions so far have been for continuous variables (PDFs). This one is discrete (PMF). 

We've already been using it for coin flips; it's used for binary (0 or 1) outcome. 

Its parameters are: 

* *n*: number of trials
* *p*: probability of outcome of 1
* *size*: number of experiments with *n* trials each

## Multiple Choice Exercises: Calculate and Select your best solution (Each Question is one Mark)

1. What is the probability of drawing the ace of spades twice in a row? (Assume that any card drawn on the first draw will be put back in the deck before the second draw.)

A. 0.037%

B. 0.050%

C. 0.010%

D. 0.100%

B
2. You draw a card from a deck of cards. After replacing the drawn card back in the deck and shuffling thoroughly, what is the probability of drawing the same card again? 

 A. 0.010
 
 B. 0.018
 
 C. 0.081
 
 D. 0.019

 A

3. Use $n \choose k$ to calculate the probability of throwing three heads in five coin tosses.

A. 0.3125

B. 0.5210

C. 0.3100

D. 0.2135

4.  Which of the following Expressions below correspond to the statement: **the probability that it is Monday given that it is raining**?

A. Pr(Monday|rain)

B. Pr(rain|Monday)

C. Pr(rain|Monday)Pr(Monday)

D. Pr(Monday|rain) Pr(rain)/Pr(Monday)

A

5. Which of the following Expressions below correspond to the statement: **Pr(Monday|rain)**?

A. The Probability of rain on Monday

B. The Probability of rain given that it is Monday

C. The Probability that it is Monday, given that it is raining

D. The probability that it is Monday and that it is raining

C

6. Which of the following Expressions below correspond to the statement: **the probability of rain on Monday**?

A. Pr(rain)

B. Pr(rain|Monday)

C. Pr(Monday|rain)

D. Pr(rain, Monday)/Pr(Monday)
A

7. A professor thinks students who live on campus are more likely to get **A**s in the probability course. To check this theory, the professor combines the data from the past few years. 600 students have taken the course, 120 students have gotten As, 200 students lived on campus, 80 students lived off campus and got As.

A. Pr(AnB) = Pr(A)+Pr(B)

B. Pr(AnB) = Pr(A) * Pr(B) - Pr(AnB)

C. Pr(AnB) = Pr(A) * Pr(B)

D. Pr(AnB) = (Pr(A) * Pr(B))/(Pr(B))

8. Does this data suggest that "getting an A" and "living on campus" are dependent or independent?  
 
 A. Agree
 
 B. Disagree
 
 C. Neutral 
 
 D. Insufficient Information provided

 A 

9. Suppose that I want to purchase a smart phone. I can choose either a large or a small screen; a 64GB, 128GB, or 256GB storage capacity, and a black or white cover. 

(a).How many different options do I have?

 A. 13
 
 B. 0
 
 C. 9/10 
 
 D. Insufficient Information provided

 A
 
 10. A block of 100 bits is trasmitted in a binary channel with a probability of bit error **P= 0.002**

(a) If the block has 1 or fewer errors,then the receiver accepts the block. What is the **probability** that the block is accepted?

A. 0.735

B. 0.501

C. 0.350

D. 0.100

C

(b) If the block has more that 1 errors, then the block is retrasmitted.
What is the **probability** that 4 blocks are trasmitted?

(1) 0.013

(2) 0.0350

(3) 0.430

(4) 0.500

2
"""

# Given an experimental setup below

n = 5
n_experiments = 1000

"""#### ... and that we are dealing with a Fair coin (p = 0.5), Then"""

heads_count = np.random.binomial(n, 0.5, n_experiments)
heads, event_count = np.unique(heads_count, return_counts=True)
event_proba = event_count/n_experiments

import matplotlib.pyplot as plt
plt.bar(heads, event_proba, color='mediumpurple')
plt.xlabel('Heads flips (out of 5 tosses)')
_ = plt.ylabel('Event probability')

"""Then, Technically, binomial distributions are created by sampling $n>1$ "Bernoulli trials". The **Bernoulli** distribution is equivalent to the binomial distribution where $n=1$:

### and ...
"""

import numpy as np
np.random.binomial(1, 0.5)

"""Select **ALL** possible real-world examples of a binomial distribution basing on its key properties from the list below:

* Making it to work on time
* Candidate being invited to interview
* Epidemiology: probability of death or catching disease
* Number of new hires in a month
* Extreme weather events, e.g., maximum rainfall in a day
* Time between requests to access Wikipedia pages
"""

## Supply your selections here



"""## b). Poisson Distribution

**Poisson** is a third widely-used distribution for discrete random variables and it's the final distribution we'll cover.

It's named after French mathematician Simeon Denis Poisson and is used for count data, e.g.: 

Select **ALL** possible real-world examples of a poisson distribution basing on its key properties from the list below:

* Number of cars that drive by in a minute
* Number of guests at restaurant in an evening
* Number of new hires in a month
* Child births in the national referral hospital on any particular day
* The number of a jupyter notebook to run optimally
"""

## Supply your selections here.

"""## c). Gaussian or Normal Distribution

Gaussian or Normal distribution is a **standard normal distribution** (a.k.a., standard Gaussian distribution). Normal distributions can be denoted with the *math calligraphy* font as $\mathcal{N}(\mu, \sigma^2)$, thus the standard normal distribution can be denoted as $\mathcal{N}(0, 1)$. 

(N.B.: $\sigma^2 = \sigma$ in this case because $1^2 = 1$.)

Normal distributions are by far the most common distribution in statistics and machine learning. They are typically the default option, particularly if you have limited information about the random process you're modeling, because: 

1. Normal distributions assume the greatest possible uncertainty about the random variable they represent (relative to any other distribution of equivalent variance). Details of this are beyond the scope of this tutorial. 
2. Simple and very complex random processes alike are, under all common conditions, normally distributed when we sample values from the process. Since we sample data for statistical and machine learning models alike, this so-called **central limit theorem** (covered next) is a critically important concept.

Sellect **ALL** Possible real-world examples of a Gaussian Distribution basing on its characteristics: 

* Probability of heads across *n* tosses (PMF; $n = 5$ earlier, $n = 100$ below)
* Sum of di(c)e rolls (PMF)
* Height of adult women
* Height of adult men
* Education test scores, e.g., Mathematical Computing scores you will obtain today
* Number of Children ever born 
* The Spread of COVID-19 disease in a given community
"""

## Supply your selections here.

"""# Linear Algebra

*Review of Introductory Linear Algebra*

* Modern Linear Algebra Applications
* Tensors, Vectors, and Norms
* Matrix Multiplication
* Matrix Inversion
* Identity, Diagonal and Orthogonal Matrices
"""

# Setup: As an example

import numpy as np

y = np.ones(3) 
y

"""### Question 4: Given an n-dim array with enteries: 25, 2, 5;

* 1. Generate a numpy array x from the given entries
* 2. What is the shape of the array x
* 3. What is its transpose
* 4. Compute its $L^2$ Norm
"""

import numpy as np

x=np.array([25,2,5])
#shape
print(np.shape(x))
#transpose
x.T
#norm
from numpy import linalg
x=linalg.norm(x)
print(x)





"""## Question 5: Given an n-darray X = np.array([[25, 2], [5, 26], [3, 7]])

* 1. Generate its shape
* 2. What is the transpose of the array
* 3. Generate a new n-darray of X scaled up by integer 3 (Hint: note that scalars are applied on each element of a matrix)
* 4. Generate a new matrix A = ([[3, 4], [5, 6], [7, 8]]). Compute the matrix multiplication of matrices X and A (note the condition for matrix multiplication must satisfy a certain rule)
* 5. Compute the inverse of the result of multiplication of matrices (A and X)
"""

X=np.array([[25,2],[5,26],[3,7]])
print(np.shape(X))
#transpose
X.T
#Scale up
Z=X+3
print(Z)
#NO.4
X=np.array([[25,2],[5,26],[3,7]])
A= np.array([[3,4],[5,6],[7,8]])
B=np.dot(A,X)
print(B)









"""## Question 6: Construct a matrix below ; 

$$\left[\begin{array}{ccc} 1 & 0.2 & 0.5 \\ 0.2 & 1 & 0.8 \\ 0.5 & 0.8 & 1 \end{array}\right]$$

as a NumPy array.


(a). Compute an Inversion of the matrix **Transpose** 

(b). Computer the **determinant** of the matrix if possible 
"""

import numpy as np

x=np.array([[[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]]])
print(x)
from numpy import linalg
#determinant
x=linalg.det(x)
x
#invesion

"""## Optional Section: Attempting these extra questions yields extra marks as indicated in the brackets

## 7. Compute the Mean, variance, median, mode of a uniform random variable (10 marks)
"""

import numpy as np
x=np.random.uniform(low=0.0,high=1.0,size=None)
print(x)

"""## GOOD LUCK """

